[book]
title = "laufey"
description = "Build cross-platform apps with web technologies and your choice of browser engine."
authors = ["Divy Srivastava"]
src = "docs"
language = "en"

[output.html]
git-repository-url = "https://github.com/littledivy/laufey"
edit-url-template = "https://github.com/littledivy/laufey/edit/main/{path}"
default-theme = "light"
preferred-dark-theme = "navy"
no-section-label = true

[output.html.fold]
enable = true
level = 1
